DROP DATABASE gold;
COMMIT;

CREATE DATABASE gold;
USE gold;

CREATE TABLE USER_ROLE(
ID INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(25) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO USER_ROLE(Name) VALUES('Admin');
INSERT INTO USER_ROLE(Name) VALUES('Customer');

CREATE TABLE COUNTRIES(
COUNTRY_ID INT NOT NULL AUTO_INCREMENT,
COUNTRY_NAME VARCHAR(25) NOT NULL,
PRIMARY KEY(COUNTRY_ID)
);

INSERT INTO countries (COUNTRY_NAME) VALUES ('Afghanistan');
INSERT INTO countries (COUNTRY_NAME) VALUES ('France');
INSERT INTO countries (COUNTRY_NAME) VALUES ('Germany');
INSERT INTO countries (COUNTRY_NAME) VALUES ('Luxembourg');
INSERT INTO countries (COUNTRY_NAME) VALUES ('Pakistan');
INSERT INTO countries (COUNTRY_NAME) VALUES ('Romania');
INSERT INTO countries (COUNTRY_NAME) VALUES ('USA');

CREATE TABLE ppl 
(
PERSON_ID INT NOT NULL AUTO_INCREMENT, 
First_Name VARCHAR(25) NOT NULL, 
Second_Name VARCHAR(25) NOT NULL,
Age INT,
UserName VARCHAR(25) NOT NULL UNIQUE,
Password VARCHAR(255) NOT NULL,
Nationality INT NOT NULL,
User_type INT NOT NULL,
PRIMARY KEY (PERSON_ID),
FOREIGN KEY (Nationality) REFERENCES COUNTRIES(COUNTRY_ID),
FOREIGN KEY (User_type) REFERENCES USER_ROLE(ID)
);

CREATE TABLE Products
(
ID INT NOT NULL AUTO_INCREMENT,
NAME varchar(50),
Description varchar(500),
Price INT(10),
Picture varchar(50),
PRIMARY KEY (ID)
);